### ISSUE TITLE
Trac Tables breaking out of container

### ISSUE THREAD

**Issue by wldcordeiro** [django/djangoproject.com#226]
At 1920x1200 on Firefox this is how the Trac table is showing up for a ticket search.
![screen shot 2014-12-17 at 16 27 10](https://cloud.githubusercontent.com/assets/580982/5481090/afc7f70c-8609-11e4-9b10-5c008470693e.png)

**Comment by timgraham** [comment]
This is fixed now that the sidebar only appears on the Trac welcome page.

**Comment by renatooliveira** [comment]
Hi! This is still happening

1366 x 768 Chrome 

![screenshot from 2015-04-10 16 54 02](https://cloud.githubusercontent.com/assets/613912/7097303/5221b1d6-dfa2-11e4-92f8-763f6e8afaec.png)
