### ISSUE TITLE
Approving a feed from the admin changelist page crashes

### ISSUE THREAD

**Issue by timgraham** [django/djangoproject.com#511]
The error is:
```
SubscriptionError: ('Error during request to hub https://superfeedr.com/hubbub for topic
http://timonweb.com/taxonomy/term/60/all/feed: Make sure your callback returns a 2XX
status code. You returned 404 to https://www.djangoproject.com/subscriber/846/?
hub.mode=subscribe&hub.topic=http%3A%2%2Ftimonweb.com%2Ftaxonomy%2Fterm%2F60%2Fall%2Ffeed&
hub.challenge=xedbjdr6bt9&hub.lease_seconds=315360000', <Subscription: Subscription object>,
<Response [422]>)
```
I think the issue is that because `ModelAdmin.changeform_view()` uses `@transaction.atomic`, the `Subscription` object that is created during the request isn't accessible at the point later in the request when the query to superfeedr is issued (which then pings back to `djangoproject.com/subscriber/<new_id>/`).

**Comment by timgraham** [comment]
@aaugustin -- did I describe the problem in an understandable fashion? Any ideas? It seems like a possible use case for transaction hooks, however, the [code in question](https://github.com/brutasse/django-push/blob/f86f5372158751aef6a30dc1263d420ca084c2bc/django_push/subscriber/models.py#L38-L40) is in a third-party app.

**Comment by aaugustin** [comment]
Usually I'd recommend `@transaction.non_atomic_requests` but IIRC it won't work because the admin enforces its own transaction on top of `ATOMIC_REQUESTS`. Transaction hooks won't work because Superfeedr will still ping before the transaction has committed. I don't have a great suggestion right now.

**Comment by carljm** [comment]
@aaugustin I'm not sure what you mean by "Transaction hooks won't work because Superfeedr will still ping before the transaction has committed." The point of using a transaction hook would be to not even notify Superfeedr in the first place until after the transaction is committed, meaning Superfeedr couldn't possibly ping back too soon.

ISTM this is a straightforward case - just needs a pull request on the third-party project to have it use a transaction hook if on a recent-enough Django version (and I assume dp.com uses a recent-enough Django version). Now that transaction hooks are built in, there's zero reason for a project like django-push not to use them (if available) in a case like this.

**Comment by aaugustin** [comment]
Ah, right, I hadn't figured out the correct way to use transaction hooks here. That was pre-coffee.

**Comment by timgraham** [comment]
I think this should be fixed now that we're using Django 1.9 and django-push 0.8, but it's to be confirmed when we have a feed to approve.

**Comment by timonweb** [comment]
Hi Guys, a week ago or so, I submitted a feed but still can't see it in Community blogs section, could you please check? The feed url is http://timonweb.com/feed/tag/django_planet/ It may be a nice test for your fix :)

**Comment by timgraham** [comment]
I check the pending feeds occasionally. I approved it now.
